### PR TITLE
XCode 7.2 Support

### PR DESCRIPTION
**Pull request by Nekrich**

### CODE REVIEW

**Comment by francesco-garcia-movile** [comment]
:+1:

**Comment by fpg1503** [comment]
:+1:

**Comment by otaran** [comment]
:+1:

**Comment by chavira** [comment]
👍

**Comment by Jasdev** [comment]
Sorry if this is a question that has been answered before, but is there a way to make Polychromatic compatible with all future versions of Xcode? I'd be glad to help with this, if someone can point me in the right direction! :smile:

**Comment by kolinkrewinkel** [comment]
@Jasdev Not that I know of; they used to be compatible indefinitely but they intentionally added this system.

**Pull request merged**
